# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://liquidmarkup.org" # the base hostname & protocol for your site
markdown: kramdown
permalink: /:year/:month/:day/:basename:output_ext
collections:
  - filters
exclude:
  - README.md
  - CNAME
  - node_modules
keep_files: ['css']
